2023-12-23 00:19:48,239 INFO    StreamThr :85071 [internal.py:wandb_internal():86] W&B internal server running at pid: 85071, started at: 2023-12-23 00:19:48.238666
2023-12-23 00:19:48,241 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status
2023-12-23 00:19:48,244 INFO    WriterThread:85071 [datastore.py:open_for_write():85] open: /root/Projects/Kaggle/linking-writing/wandb/run-20231223_001948-d8qxtbes/run-d8qxtbes.wandb
2023-12-23 00:19:48,245 DEBUG   SenderThread:85071 [sender.py:send():382] send: header
2023-12-23 00:19:48,289 DEBUG   SenderThread:85071 [sender.py:send():382] send: run
2023-12-23 00:19:48,671 ERROR   SenderThread:85071 [internal_api.py:execute():373] 404 response executing GraphQL.
2023-12-23 00:19:48,671 ERROR   SenderThread:85071 [internal_api.py:execute():374] {"errors":[{"message":"entity your_wandb_username not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-23 00:19:48,671 ERROR   SenderThread:85071 [sender.py:send_run():987] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 985, in send_run
    self._init_run(run, config_value_dict)
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 1027, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2212, in upsert_run
    response = self.gql(
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/util.py", line 965, in check_retry_fn
    return fallback_retry_fn(e)
  File "/root/miniconda3/envs/torch/lib/python3.10/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-23 00:19:53,676 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:19:58,676 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:03,677 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:08,678 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:13,679 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:18,680 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:23,681 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:25,968 INFO    StreamThr :85071 [internal.py:wandb_internal():86] W&B internal server running at pid: 85071, started at: 2023-12-23 00:20:25.967535
2023-12-23 00:20:25,970 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status
2023-12-23 00:20:25,972 INFO    WriterThread:85071 [datastore.py:open_for_write():85] open: /root/Projects/Kaggle/linking-writing/wandb/run-20231223_002025-i6rr4f33/run-i6rr4f33.wandb
2023-12-23 00:20:25,973 DEBUG   SenderThread:85071 [sender.py:send():382] send: header
2023-12-23 00:20:25,976 DEBUG   SenderThread:85071 [sender.py:send():382] send: run
2023-12-23 00:20:26,673 INFO    SenderThread:85071 [dir_watcher.py:__init__():211] watching files in: /root/Projects/Kaggle/linking-writing/wandb/run-20231223_002025-i6rr4f33/files
2023-12-23 00:20:26,673 INFO    SenderThread:85071 [sender.py:_start_run_threads():1136] run started: i6rr4f33 with start time 1703290825.966679
2023-12-23 00:20:28,682 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:30,977 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:20:31,674 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:33,683 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:35,978 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:20:36,675 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:38,684 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:40,979 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:20:41,676 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:43,685 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:45,980 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:20:46,677 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:48,686 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:50,981 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:20:51,678 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:53,687 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:55,982 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:20:56,679 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:20:58,688 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:00,983 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:01,680 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:03,688 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:05,985 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:06,681 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:08,689 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:10,986 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:11,681 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:13,690 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:15,987 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:16,682 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:18,691 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:20,988 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:21,683 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:23,692 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:25,989 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:26,684 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:28,693 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:30,990 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:31,684 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:33,694 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:35,991 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:36,685 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:38,694 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:40,992 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:41,686 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:43,695 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:45,992 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:46,687 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:48,696 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
2023-12-23 00:21:50,994 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: keepalive
2023-12-23 00:21:51,687 DEBUG   HandlerThread:85071 [handler.py:handle_request():146] handle_request: status_report
